#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Source tmpzshrc
if [[ -s "${ZDOTDIR:-$HOME}/.tmpzshrc" ]]; then
    source "${ZDOTDIR:-$HOME}/.tmpzshrc"
fi

# Base16 Shell
BASE16_SHELL="$HOME/.base16-shell"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"
if [[ -s "$BASE16_SHELL" ]]; then
    # Applies one of these themes each day.
    THEMES="mocha apathy tube railscasts atelier-dune atelier-lakeside atelier-estuary atelier-savanna"
    CNT=`echo $THEMES | wc -w`
    IND=$((`date +%j`%$CNT+1))
    TODAY_THEME=`echo $THEMES | cut -d " " -f $IND`
    BASE16_THEME_FILE="$BASE16_SHELL/scripts/base16-$TODAY_THEME.sh"
    [[ -s $BASE16_THEME_FILE ]] && source $BASE16_THEME_FILE
fi

# Enable Shell Extension for Desk (https://github.com/jamesob/desk)
if [[ -s "$HOME/.zdesk" ]]; then
    fpath=($HOME/.zdesk/shell_plugins/zsh $fpath)
fi

# Activate Comment in Interactive mode
setopt interactivecomments
# Hook for desk activation
[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true
