#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Source tmpzshrc
if [[ -s "${ZDOTDIR:-$HOME}/.tmpzshrc" ]]; then
    source "${ZDOTDIR:-$HOME}/.tmpzshrc"
fi
